---
title: "R Notebook"
output: html_notebook
---

```{r}
library(data.table)
library(tidyverse)
```

```{r}
train <- fread("~/git/zbiory/otodom/train-small3.csv", 
               col.names = c("id", "created_at_first", "category",
                             "is_business", "district_id", "city_id", "region_id", 
                             "params", "title", "price")) %>%
  mutate(floor_area = str_extract(params, "m<=>\\d{1,}(\\.\\d{1,2})?"),
         floor_area = str_extract(floor_area, "\\d{1,}(\\.\\d{1,2})?"),
         floor_area = as.numeric(floor_area),
         rooms_num = str_extract(params, "rooms_num<=>\\d{1,}"),
         rooms_num = str_extract(rooms_num, "\\d{1,}"),
         rooms_num = as.numeric(rooms_num),created_at_first = ymd_hms(created_at_first),
         yq = quarter(created_at_first, with_year = T),
         market_primary = str_detect(params, "primary")) %>%
  filter(price > quantile(price, 0.01), price < quantile(price, 0.99)) %>%
  filter(floor_area > quantile(floor_area, 0.01), 
         floor_area < quantile(floor_area, 0.99)) %>%
  filter(city_id == 1, category == "Mieszkanie na sprzedaż", market_primary == FALSE)

train
```

First hedonic regression model with time-dummy variables

```{r}
m1 <- lm(formula = log(price) ~ floor_area + rooms_num + is_business + factor(yq),
         data = train)
summary(m1)

round(exp(coef(m1))[5:8]*100,2)

round(exp(confint(m1))*100,2)
```


```{r}
train %>% 
  group_by(yq) %>% 
  summarise(m = mean(price),
            av_floor = mean(floor_area)) %>% 
  ungroup() %>%
  mutate(index = m/first(m)*100)
```

Imputation method

1. create subsets for each time period
2. create a model for t+1 
3. predict based on model for t+1 for data from period t
4. then we calculate index 

$$
\sum  predicted_{t+1}(x_t) / \sum prices_t
$$

```{r}
train_q1 <- train %>% filter(yq == "2018.1")
train_q2 <- train %>% filter(yq == "2018.2")
m2 <- lm(formula = log(price) ~ floor_area + rooms_num + is_business, data = train_q2)
train_q1$price_pred <- exp(predict(m2, newdata = train_q1))
sum(train_q1$price_pred)/ sum(train_q1$price)*100
```

